-- Secuencia para ID motivo_devolución

CREATE SEQUENCE sec_motivo_devolucion
START WITH  0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

-- Secuencia para ID estado_físico

CREATE SEQUENCE sec_estado_físico
START WITH  0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

-- Secuencia para ID estado_crecimiento

CREATE SEQUENCE sec_estado_crecimiento
START WITH  0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

-- Secuencia para ID tipo_mascota

CREATE SEQUENCE sec_tipo_mascota
START WITH  0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

-- Secuencia para ID raza_mascota

CREATE SEQUENCE sec_raza_mascota
START WITH  0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

-- Secuencia para ID mascota

CREATE SEQUENCE sec_mascota
START WITH  0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

-- Secuencia para ID tamanno_mascota

CREATE SEQUENCE sec_tamanno_mascota
START WITH  0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

-- Secuencia para ID color_mascota

CREATE SEQUENCE sec_color_mascota
START WITH  0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

-- Secuencia para ID enfermedades_mascota

CREATE SEQUENCE sec_enfermedades_mascota
START WITH  0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

-- Secuencia para ID tratamientos_enfermedades

CREATE SEQUENCE sec_tratamientos_enfermedades
START WITH  0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

-- Secuencia para ID medicinas

CREATE SEQUENCE sec_medicinas
START WITH  0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

-- Secuencia para ID medicinas

CREATE SEQUENCE sec_medicinas
START WITH  0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

-- Secuencia para actividad_fisica

CREATE SEQUENCE sec_actividad_fisica
START WITH  0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

-- Secuencia para ID estado_adopcion

CREATE SEQUENCE sec_estado_adopcion
START WITH  0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

-- secuencia para ID facilidad_entrenamiento

CREATE SEQUENCE sec_facilidad_entrenamiento
START WITH     0
INCREMENT BY   1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

-- secuencia para ID nivel_energía

CREATE SEQUENCE sec_nivel_energia
START WITH     0
INCREMENT BY   1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;
