--secuencias para ids personas
CREATE SEQUENCE sec_Items
START WITH     0
INCREMENT BY   1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sec_Enunciados
START WITH     0
INCREMENT BY   1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sec_Preguntas
START WITH     0
INCREMENT BY   1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sec_Formularios
START WITH     0
INCREMENT BY   1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sec_Tipo_Formulario
START WITH     0
INCREMENT BY   1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sec_Preguntas_Formularios
START WITH     0
INCREMENT BY   1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sec_Formularios_Respuestas
START WITH     0
INCREMENT BY   1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sec_Formularios_Aceptados
START WITH     0
INCREMENT BY   1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;